[package]
name = "pomodoro"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
beep = "0.3.0"
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
rodio = "0.21.1"
serde = "1.0.219"
serde_json = "1.0.141"
